# Generated by Django 4.0.2 on 2022-02-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_en_us',
            field=models.TextField(help_text='The body/contents of the article', null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_es',
            field=models.TextField(help_text='The body/contents of the article', null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_sr',
            field=models.TextField(help_text='The body/contents of the article', null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_en_us',
            field=models.CharField(help_text='The summary of the article (max. 500 characters)', max_length=500, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_es',
            field=models.CharField(help_text='The summary of the article (max. 500 characters)', max_length=500, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_sr',
            field=models.CharField(help_text='The summary of the article (max. 500 characters)', max_length=500, null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sr',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
